### ISSUE TITLE
Compatibility Netbox v4

### ISSUE THREAD

**Issue by nikor30** [mlebreuil/netbox-contract#139]
Hi if I am not wrong installation went fine but I can´t not see it in the gui or anywhere...

Netbox v4.0.5

**Comment by jinu18** [comment]
> Hi if I am not wrong installation went fine but I can´t not see it in the gui or anywhere...
> 
> Netbox v4.0.5

It works for me , no issues

**Comment by mlebreuil** [comment]
Sorry for the late reply. Did not see any issue either.

**Comment by nikor30** [comment]
Hi a python modle was missing for me "drf_yasg" after manualy installing it worked

**Comment by mlebreuil** [comment]
This will be added to the requiremets in the future release
