### ISSUE TITLE
Add the invoice lines model

### ISSUE THREAD

**Issue by mlebreuil** [mlebreuil/netbox-contract#140]
Currently invoice lines are registered as part of the "dimensions" field. 
Adding another model would ease calculation and import from the ERP.

**Comment by zchencq** [comment]
We have the same need for this and will be glad to see this issue is discussed further. :)

A dedicated data model for account/cost center will be very useful.
```
'default_accounting_dimensions':{
            "account": "", 
            "project": "", 
            "cost center": ""
        }
```

**Comment by mlebreuil** [comment]
That make sense. I was afraid that it would make entering invoices too long initially. Currently I am working on the option to attach an invoice template to a contract. How would you see this model? What would be your needs?

**Comment by zchencq** [comment]
In fact, we'd like to have this cost center model linked to "Contract" instead of Invoice. It will be more efficient for our data. Coz no need to fill in cost center everytime an invoice is created and we do have many invoices. What do you think of this ?

**Comment by zchencq** [comment]
regarding the details of cost center code model, quite simple one 

- * CostCenter
- ProfitCenter (our specific)
- Description
- CompanyName
- SAPCode
