### ISSUE TITLE
Please allow to Add Annual Billing Rate

### ISSUE THREAD

**Issue by jinu18** [mlebreuil/netbox-contract#142]
Rarely a contract is done monthly. It should be our choice to select annual or per month. Even if manually divide the amount by 12 it gets decimal places

**Comment by mlebreuil** [comment]
I originally created the plugin for telecom contracts which are very often expressed as monthly recuring cost and non recuring costs. The related invoices have to be reconciled on a monthly basis. While for yearly contract its only once a year. Currently it is not so trivial (at least for me) to give the option to enter the contract value as a yearly amount. But if you would like to propose a MR. you are welcome.

**Comment by MROSSFTEK** [comment]
i concur with jinu18. 
for US, we want to put in MRC for some, and YRC for others, so when we look at our list, we see a TRUE YRC. your plugin, while awesome, appears to take MRC and multiply it by 12. SOMETIMES that's not accurate as a MRC can change .
