### ISSUE TITLE
Invoices can not be updated/created with associated Contracts (list) 

### ISSUE THREAD

**Issue by zchencq** [mlebreuil/netbox-contract#165]
Invoice can be linked to a list of contracts, but when using netbox API , it's blocked due to the below error

pynetbox.core.query.RequestError: The request failed with code 500 Internal Server Error: {'error': 'The `.update()` method does not support writable nested fields by default.\nWrite an explicit `.update()` method for serializer `netbox_contract.api.serializers.InvoiceSerializer`, or set `read_only=True` on nested serializer fields.', 'exception': 'AssertionError', 'netbox_version': '4.0.5', 'python_version': '3.11.6'}

**Comment by zchencq** [comment]
@mlebreuil any idea where to fix ?  btw, I'm using [netbox-contract] v2.1.2

**Comment by zchencq** [comment]
another issue is tha in GUI invoice edit view, "contracts" dropdown box search doesn't work properly

**Comment by zchencq** [comment]
@mlebreuil  hello thanks for your update, but I'm still not able to update invoice with its associated Contracts via pynetbox.
There are 2 issues blocking me (coz I'm using API for bulk data import, so I need to use filter() + update())

1. nb.plugins.contracts.invoices.get() or nb.plugins.contracts.invoices.filter() methods are not working , it always return the full list and ignore the filter value , for example  nb.plugins.contracts.invoices.filter(number="1232123")
2. use update seems always complains the below key error
pynetbox.core.query.RequestError: The request failed with code 500 Internal Server Error: {'error': "'template'", 'exception': 'KeyError', 'netbox_version': '4.0.9', 'python_version': '3.11.6'}

**Comment by zchencq** [comment]
btw the filter() issue also exists for contracts --> nb.plugins.contracts.contracts.filter()

**Comment by zchencq** [comment]
kindly request reopen the issue @mlebreuil  , let me know! thanks a lot in advance !

**Comment by mlebreuil** [comment]
Filtering: You cannot filter on any field. From the netbox api documentation, accessible through the "REST API documentation" icon at the bottom of the page,  you can figure out which field are available for filtering. I will try to include more in the next release. Fell free to give some feed backs on the needs.

**Comment by mlebreuil** [comment]
update:  Some fields are mandatory and here again you can use the api documentation to figure out which. From what you mention I assume that you must set the "template" field. I that on existing records the value is null while it should be set on update. I was able to create and update invoices through the API.

**Comment by zchencq** [comment]
> Filtering: You cannot filter on any field. From the netbox api documentation, accessible through the "REST API documentation" icon at the bottom of the page, you can figure out which field are available for filtering. I will try to include more in the next release. Fell free to give some feed backs on the needs.

Thanks for a quick reply. where is the page you refer to?  for Contract and invoice, I tried most of the available fields (basic ones like id, name, number), none of them seems work. it always returns to a "full list"

**Comment by zchencq** [comment]
> template



> update: Some fields are mandatory and here again you can use the api documentation to figure out which. From what you mention I assume that you must set the "template" field. I that on existing records the value is null while it should be set on update. I was able to create and update invoices through the API.

btw how is the "template" field used? I just notice it's a newly added field for invoice, thanks
