### ISSUE TITLE
upgrade version

### ISSUE THREAD

**Issue by MROSSFTEK** [mlebreuil/netbox-contract#187]
forgive my dumb question.. but the latest version is 2.25. i am running 2.24.. how do you upgrade to the latest version?

**Comment by mlebreuil** [comment]
Same as the [installation](https://mlebreuil.github.io/netbox-contract/).  

```
source /opt/netbox/venv/bin/activate
pip install netbox-contract --upgrade
cd /opt/netbox/netbox/
python3 manage.py migrate

```
