### ISSUE TITLE
internal partie filed 

### ISSUE THREAD

**Issue by skynets4** [mlebreuil/netbox-contract#36]
Hello. Can you answer of my question.
What does you mean "Internal partie" in contracts from?
This field have two value "Nagravision SARL" and "Nagra USA".

**Comment by mlebreuil** [comment]
"Internal partie" reference the legal entity of your organization which is the counterpart in the contract to the external partie.
The values that your see were used at development time and should be overridden  in the Netbox configuration.py file.  

```python
# configuration.py
FIELD_CHOICES = {
    'netbox_contract.Contract.internal_partie': (
        ('Entity1', 'Entity1', 'green'),
        ('Entity2', 'Entity2, 'green'),
    )
}
```
