### ISSUE TITLE
Allow for different currencies to be entered as plain text

### ISSUE THREAD

**Issue by zeddD1abl0** [mlebreuil/netbox-contract#79]
Hi,

Can I please request that the "Currency" field be something that can be easily updated within the app. Either by making it a text field, or by allowing us to add currencies when it is useful to us.

**Comment by mlebreuil** [comment]
Hi , customizing the list of currencies is already possible.  
You need to add something similar to the below in the configuration.py file.
check [Netbox documentation](https://docs.netbox.dev/en/stable/plugins/development/models/#dynamic-configuration)

```python
# configuration.py
FIELD_CHOICES = {
    'netbox_contract.Contract.currency': (
       ('usd', 'USD'),
       ('eur', 'EUR'),
       ('chf', 'CHF'),
    )
}

```
